name: Fabric Summarize Transcript
on:
  push:
    paths:
      - 'transcripts/**'  # Se activará cuando se añadan archivos en la carpeta transcripts

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:          # Agregar permisos explícitos
      contents: write    # Permiso para escribir en el repositorio
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalamos las dependencias necesarias directamente
          pip install "openai>=1.0.0" python-dotenv requests typing-extensions pyyaml groq

      - name: Clone Fabric
        run: |
          git clone https://github.com/danielmiessler/fabric.git

      - name: Process Transcript
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python scripts/process_transcript.py
          
      - name: Commit Summary
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add summaries/
          git commit -m "Add automated summary" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}